#!/bin/bash

#########################################################################################
## Script file to run the dnsserver program to download the data from the URL provided
#########################################################################################
## Must be run by root user or using 'sudo'
## ./dnsserver [url]
## url is a required field that needs to be provided to download the data
## the data related to the URL is downloaded in the same directory where the program is being run
if [ $# -lt 4 -o $# -gt 4 ]
then
    printf "Please enter the command in the following format -p <port> -n <name>"
    exit 0
fi

p=$2
n=$4

# Setup venv and install dependencie
python3 -m venv testvenv
source testvenv/bin/activate
pip3 install dnslib
pip3 install geoip2
## Run the python program to download the data from the URL provided
python3 dnsserver.py -p "$p" -n "$n"