#!/bin/bash

#########################################################################################
## Script file to run the dnsserver program to download the data from the URL provided
#########################################################################################
## Must be run by root user or using 'sudo'
## ./dnsserver [url]
## url is a required field that needs to be provided to download the data
## the data related to the URL is downloaded in the same directory where the program is being run
if [ $# -lt 4 ] &&[ $# -gt 4 ]
then
    printf "Supported command format: -p <port> -n <name> \n"
    exit 0
fi

# Parse the command line arguments
while getopts ":p:o:" opt; do
  case $opt in
    p) port="$OPTARG"
    ;;
    o) origin_name="$OPTARG"
    ;;
    \?) printf "Invalid option -%s" "$OPTARG">&2
    ;;
  esac
done

# Check if the port number is valid
if [ "$port" -lt 1024 ] && [ "$port" -gt 65535 ]
then
    printf "Port number should be between 1024 and 65535"
    exit 0
fi

# Check if the name is valid
if [ -z "$origin_name" ]
then
    printf "Name cannot be empty"
    exit 0
fi

# Now start the server
cd p4_build || exit
printf "Starting the server on port %s with name %s \n" "$port" "$origin_name"

python3 httpserver.py -p "$port" -o "$origin_name"
