#!/bin/bash

# This script is used to deploy the CDN to the replicas and the DNS server.
# It takes the following arguments: -p <port> -o <origin> -n <name> -u <username> -i <keyfile>
# Sample usage: ./runCDN -p 25019 -o cs5700cdnorigin.ccs.neu.edu -n cs5700cdn.example.com -u cdn_project_dileep_nikhil -i /Users/dileepshah/.ssh/id_ed25519.pub

# Parse the command line arguments
while getopts ":p:o:n:u:i:" opt; do
  case $opt in
    p) port="$OPTARG"
    ;;
    o) origin="$OPTARG"
    ;;
    n) name="$OPTARG"
    ;;
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
    \?) printf "Invalid option %s" -"$OPTARG" >&2
    ;;
  esac
done

# Check if the port number is valid
if [ "$port" -lt 1024 ] && [ "$port" -gt 65535 ]
then
    printf "Port number should be between 1024 and 65535"
    exit 0
fi

# Check if the name is valid
if [ -z "$name" ]
then
    printf "Name cannot be empty"
    exit 0
fi

# Check if the username is valid
if [ -z "$username" ]
then
    printf "Username cannot be empty"
    exit 0
fi

# Check if the keyfile is valid
if [ -z "$keyfile" ]
then
    printf "Keyfile cannot be empty"
    exit 0
fi

replica_build_path="/home/$username/p4_build"

# Now read the list of DNS servers from the dns-hosts.txt file and run the deploy script on each DNS server
while IFS= read -r ip;
do
    # Run the deploy script on the DNS server
     # Run the deploy script on the replica
    printf "Running dns-server on : %s\n" "$ip"

    until ssh -n -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" chmod +x "$replica_build_path"/dnsserver;
    do
        sleep 1
    done

    until ssh -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" nohup "$replica_build_path"/dnsserver -p "$port" -n "$name" > /dev/null 2>/dev/null &
    do
        sleep 1
    done
done < dns-hosts.txt

# Now read the list of replicas from the replicas.txt file and run the deploy script on each replica
while IFS= read -r ip;
do
    # Run the deploy script on the replica
    printf "Running http-server on : %s\n" "$ip"

    until ssh -n -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" chmod +x "$replica_build_path"/httpserver;
    do
        sleep 1
    done

    until ssh -n -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" nohup "$replica_build_path"/httpserver -p "$port" -o "$origin" > /dev/null 2>/dev/null &
    do
        sleep 1
    done
done < replicas.txt

exit 0
